/**
 * @non-paper adapter — no adapters exist in arXiv 2608.26263v3.
 *
 * Bridges the skillstate runtime into OpenCode via:
 * - Prompts formatted with the skillstate XML-style skill envelope
 *   (delegates to PromptTransformer.formatForOpenCode).
 *
 * Host glue is NO LONGER GENERATED by this adapter:
 * - the plugin is the npm package `@skillstate/opencode` itself, loaded
 *   directly from the project `opencode.json`
 *   `"plugin": ["@skillstate/opencode"]` (see `SkillStatePlugin` /
 *   `createSkillStatePlugin` in `src/plugin.ts` — project-local and inert
 *   when the project has no skillstate state);
 * - skill markdown (SKILL.md) generation is host-neutral and lives in the
 *   CLI, not in the platform adapters.
 */
import type {
  SkillState,
  StatePatch,
  ProceduralSpec,
  Observation,
  PlatformAdapter,
} from '@skillstate/core';
import { PromptTransformer } from '@skillstate/core';
import { describeSchema, STATE_PATCH_CONTRACT } from '@skillstate/core';

/**
 * OpenCode platform adapter (@non-paper; see module doc).
 */
export class OpenCodeAdapter implements PlatformAdapter {
  readonly name = 'opencode';

  private transformer = new PromptTransformer({ platform: 'opencode' });

  /**
   * Produce a prompt string carrying the current state and skill
   * instructions, directing the LLM to reason and then emit a JSON block
   * with `state_patch` and `action`.
   */
  injectState(state: SkillState, spec: ProceduralSpec): string {
    const stateJson = JSON.stringify(state);
    const schemaDesc = describeSchema(spec.schema);

    return `<skill name="${spec.id}">
<instructions>${spec.instructions}</instructions>
${schemaDesc}
<state>
${stateJson}
</state>
</skill>

Respond with:

${STATE_PATCH_CONTRACT}`;
  }

  /**
   * Extract the state_patch from an LLM response containing a fenced JSON block.
   */
  extractPatch(response: string): StatePatch | null {
    return this.transformer.extractStatePatch(response);
  }

  /**
   * Extract the action string from an LLM response containing a fenced JSON block.
   */
  extractAction(response: string): string | null {
    return this.transformer.extractAction(response);
  }

  /**
   * Format the full prompt (instructions + state + observation).
   *
   * @non-paper — adapter convenience (delegates to the transformer).
   * Paper-exact callers use `PromptTransformer.formatPaper` (Appendix A.4).
   */
  formatPrompt(
    state: SkillState,
    observation: Observation,
    spec: ProceduralSpec,
  ): string {
    return this.transformer.formatForOpenCode(spec, state, observation);
  }

  /* ------------------------------------------------------------------ */
  /*  Internal helpers                                                   */
  /*  (none — the adapter is a pure prompt/parse surface; host glue is   */
  /*  the npm plugin itself, not generated code)                         */
  /* ------------------------------------------------------------------ */
}
